# Generated by Django 5.2.4 on 2026-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
