# Generated by Django 5.2.12 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the slider'),
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Hero section', 'verbose_name_plural': 'Hero sections'},
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this slide in the homepage slider'),
        ),
    ]
