# Generated by Django 5.2.12 on 2026-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
