# Generated by Django 5.2.12 on 2026-05-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_landlord_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='company_name',
            new_name='property_type',
        ),
    ]
