# Generated by Django 5.2.12 on 2026-05-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_occupied',
        ),
    ]
