# Generated by Django 5.2.12 on 2026-05-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_landlord_property_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='property_name',
        ),
    ]
