# Generated by Django 5.2.4 on 2026-05-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_title_property_property_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['property_name', '-created_at']},
        ),
    ]
