# Generated by Django 5.2.4 on 2026-05-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage commission the landlord pays to the company (0-100%)', max_digits=5),
        ),
    ]
