# Generated by Django 5.2.12 on 2026-05-27 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_landlord_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='number_of_units',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
