# Generated by Django 5.2.12 on 2026-04-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_landlord_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=30)),
                ('apartment_type', models.CharField(max_length=120)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('landlord_name', models.CharField(max_length=160)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='properties.landlord')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
