# Generated by Django 5.2.12 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenancy_type',
            field=models.CharField(
                choices=[
                    ('monthly', 'Monthly'),
                    ('quarterly', 'Quarterly'),
                    ('biannually', 'Biannually'),
                    ('yearly', 'Yearly'),
                ],
                default='monthly',
                max_length=20,
            ),
        ),
    ]
