# Generated by Django 5.2.12 on 2026-05-14 12:30

import django.db.models.deletion
from django.db import migrations, models


def assign_property_for_single_property_landlords(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    Property = apps.get_model('properties', 'Property')

    properties_by_landlord = {}
    for property_obj in Property.objects.all().only('id', 'landlord_id'):
        properties_by_landlord.setdefault(property_obj.landlord_id, []).append(property_obj.id)

    for tenant in Tenant.objects.filter(landlord__isnull=False, property__isnull=True).only('id', 'landlord_id'):
        property_ids = properties_by_landlord.get(tenant.landlord_id, [])
        if len(property_ids) == 1:
            Tenant.objects.filter(pk=tenant.pk).update(property_id=property_ids[0])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_landlord_commission_percentage'),
        ('tenants', '0002_tenant_tenancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='properties.property'),
        ),
        migrations.RunPython(assign_property_for_single_property_landlords, noop_reverse),
    ]
